name: todo
description: A new Flutter project.
publish_to: 'none'
version: 1.1.6+1

environment:
  sdk: ">=2.18.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  image_picker: ^0.8.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  timelines: ^0.1.0
  flutter_platform_widgets: ^7.0.0
  flutter_slidable: ^3.1.0
  flutter_native_splash: ^2.4.0
  auto_route: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 
  build_runner: ^2.4.10
  very_good_analysis: ^5.1.0
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0 
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon/todo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/defaultCategoryIcons/
    - assets/
    - assets/app_icon/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf     
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf      
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
     
    
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

