name: todo
description: A new Flutter project.


publish_to: 'none' 


version: 1.1.5+1

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: 
  cupertino_icons: ^1.0.2
  intl:
  image_picker: ^0.8.6
  hive_flutter:
  hive:
  path_provider:
  timelines:
  flutter_platform_widgets: 
  flutter_slidable:
  flutter_native_splash:
  firebase_core:
  # device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_lints: 
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon/todo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/defaultCategoryIcons/
    - assets/
    - assets/app_icon/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf     
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf      
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
     
    
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

